### ISSUE TITLE
Release Egeria 4 version of connector

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-connector-jdbc#70]
We should release an Egeria 4 version of this connector

This has already been tested with Snapshot, so the minimum is just to perform the release process.

The following issues would need to be addressed
 - #49
 - #62
 - outstanding PRs ready for merge (dependabot)
 
 I can do the above.
 
 We should also consider the use of deprecated function 
  - #61
  
  There are also other functional issues which have been raised and should be considered
  
  FYI @lpalashevski @lcpopa @mandy-chessell @dwolfson

**Comment by planetf1** [comment]
Note- #49 has auto closed

@lpalashevski Would you like to handle the release of the connector fully? I suspect the work will include the usual aspects of testing/release, but in addition

 - We may want to move to follow a branching model similar to that used for egeria, xtdb etc (optional)
 - It's likely the digital signing in the pipelines/gradle is not correct. I had to apply some fixes in the xtdb connector, and similar are likely needed here
 
 I think the two pragmatic options here are either
  - a) @lpalashevski & team work through this and raise any issues found 
  - b) I do a 'quick' 4.0 release, fixing up pipelines just to ensure the process works, and @lpalashevski you manage 4.1 onwards

**Comment by lpalashevski** [comment]
@planetf1 as we agreed, we were planning to handle the connector release within our team. We already have task planned but I was not aware that pipeline/gradle fix in needed. I am happy to go with option b) to ensure the process is aligned if this works for you. Then we take over from 4.1

**Comment by planetf1** [comment]
Suggestion:
 * initially make a release based on 4.0 release (optionally branching)
 * Run the release process similar to https://egeria-project.org/guides/contributor/release-process/egeria-connector-xtdb-release/ & add docs for jdbc
 * Refer to https://egeria-project.org/guides/contributor/release-process/maven-publish/ for info on the final publication of the artifacts
 * If there are issues with either the release pipeline itself, or artifact validation fails on oss.sonatype.org, then compare with the xtdb equivalents, which do work ok. Specifically with xtdb the initial pipelines were not correctly signing the artifacts
 * @mention me here if you get stuck and I'll take a look

**Comment by lpalashevski** [comment]
Release progress:

Docker images available on:
- quay.io/odpi/egeria-connector-jdbc:1.1
- docker.io/odpi/egeria-connector-jdbc:1.1

Maven central packages:
- pkg:maven/org.odpi.egeria/egeria-connector-integration-jdbc@1.1
- pkg:maven/org.odpi.egeria/egeria-connector-resource-jdbc@1.1
 
Github [Release V1.1](https://github.com/odpi/egeria-connector-jdbc/releases/tag/V1.1)  

Tested docker image and deployment on ING infra using Oracle DB integration.
Connector release process documentation is work in progress.
